import datetime

from tests.samples import TEST_RANGE_DATA
from upload.parsing import RangeDataParser


def test_range_data_parser_extracts_name():
    parser = RangeDataParser(TEST_RANGE_DATA)
    parser.extract_name()
    assert parser.session_info.name == "Donny Knight"


def test_range_data_parser_extracts_type():
    parser = RangeDataParser(TEST_RANGE_DATA)
    parser.extract_type()
    assert parser.session_info.type_ == "practice"


def test_range_data_parser_extracts_timestamp():
    parser = RangeDataParser(TEST_RANGE_DATA)
    parser.extract_timestamp()
    assert parser.session_info.timestamp == datetime.datetime(2019, 6, 29, 15, 29)


def test_range_data_parser_verifies_columns():
    parser = RangeDataParser(TEST_RANGE_DATA)
    parser.verify_columns()


def test_range_data_parser_data_by_club():
    expected = {
        "undefined": [
            [
                "1",
                "R",
                "33",
                "40.8",
                "1997",
                "258",
                "0.0",
                "0",
                "22",
                "1",
                "23",
                "2.1",
                "43.3",
                "5",
                "25",
                "1.30",
            ],
            [
                "2",
                "R",
                "32",
                "24.8",
                "2560",
                "1040",
                "2.7",
                "2",
                "18",
                "2",
                "20",
                "1.4",
                "26.2",
                "2",
                "28",
                "1.17",
            ],
            [
                "3",
                "R",
                "32",
                "39.2",
                "2051",
                "416",
                "-6.4",
                "-2",
                "21",
                "1",
                "22",
                "1.9",
                "41.7",
                "4",
                "25",
                "1.28",
            ],
        ],
        "driver": [
            [
                "1",
                "R",
                "162",
                "10.9",
                "4490",
                "1181",
                "-3.6",
                "21",
                "252",
                "7",
                "259",
                "7.4",
                "45.7",
                "38",
                "115",
                "1.42",
            ],
            [
                "2",
                "R",
                "160",
                "15.4",
                "4215",
                "1642",
                "-3.0",
                "40",
                "248",
                "8",
                "256",
                "7.7",
                "50.7",
                "45",
                "113",
                "1.42",
            ],
            [
                "1",
                "R",
                "161",
                "14.3",
                "3034",
                "615",
                "-5.9",
                "-2",
                "271",
                "10",
                "281",
                "7.5",
                "41.4",
                "39",
                "111",
                "1.45",
            ],
        ],
    }
    parser = RangeDataParser(TEST_RANGE_DATA)
    assert parser.data_by_club() == expected


def test_range_data_parser_data_rows():
    expected = [
        {
            "shot_num": "1",
            "hand": "R",
            "ball_speed": "33",
            "launch_angle": "40.8",
            "back_spin": "1997",
            "side_spin": "258",
            "side_angle": "0.0",
            "offline_distance": "0",
            "carry": "22",
            "roll": "1",
            "total": "23",
            "hang_time": "2.1",
            "descent_angle": "43.3",
            "peak_height": "5",
            "club_speed": "25",
            "pti": "1.30",
            "club": "undefined",
        },
        {
            "shot_num": "2",
            "hand": "R",
            "ball_speed": "32",
            "launch_angle": "24.8",
            "back_spin": "2560",
            "side_spin": "1040",
            "side_angle": "2.7",
            "offline_distance": "2",
            "carry": "18",
            "roll": "2",
            "total": "20",
            "hang_time": "1.4",
            "descent_angle": "26.2",
            "peak_height": "2",
            "club_speed": "28",
            "pti": "1.17",
            "club": "undefined",
        },
        {
            "shot_num": "3",
            "hand": "R",
            "ball_speed": "32",
            "launch_angle": "39.2",
            "back_spin": "2051",
            "side_spin": "416",
            "side_angle": "-6.4",
            "offline_distance": "-2",
            "carry": "21",
            "roll": "1",
            "total": "22",
            "hang_time": "1.9",
            "descent_angle": "41.7",
            "peak_height": "4",
            "club_speed": "25",
            "pti": "1.28",
            "club": "undefined",
        },
        {
            "shot_num": "4",
            "hand": "R",
            "ball_speed": "162",
            "launch_angle": "10.9",
            "back_spin": "4490",
            "side_spin": "1181",
            "side_angle": "-3.6",
            "offline_distance": "21",
            "carry": "252",
            "roll": "7",
            "total": "259",
            "hang_time": "7.4",
            "descent_angle": "45.7",
            "peak_height": "38",
            "club_speed": "115",
            "pti": "1.42",
            "club": "driver",
        },
        {
            "shot_num": "5",
            "hand": "R",
            "ball_speed": "160",
            "launch_angle": "15.4",
            "back_spin": "4215",
            "side_spin": "1642",
            "side_angle": "-3.0",
            "offline_distance": "40",
            "carry": "248",
            "roll": "8",
            "total": "256",
            "hang_time": "7.7",
            "descent_angle": "50.7",
            "peak_height": "45",
            "club_speed": "113",
            "pti": "1.42",
            "club": "driver",
        },
        {
            "shot_num": "6",
            "hand": "R",
            "ball_speed": "161",
            "launch_angle": "14.3",
            "back_spin": "3034",
            "side_spin": "615",
            "side_angle": "-5.9",
            "offline_distance": "-2",
            "carry": "271",
            "roll": "10",
            "total": "281",
            "hang_time": "7.5",
            "descent_angle": "41.4",
            "peak_height": "39",
            "club_speed": "111",
            "pti": "1.45",
            "club": "driver",
        },
    ]
    parser = RangeDataParser(TEST_RANGE_DATA)
    assert parser.data_rows() == expected


def test_range_data_parser_json():
    expected = [
        {
            "shot_num": "1",
            "hand": "R",
            "ball_speed": "33",
            "launch_angle": "40.8",
            "back_spin": "1997",
            "side_spin": "258",
            "side_angle": "0.0",
            "offline_distance": "0",
            "carry": "22",
            "roll": "1",
            "total": "23",
            "hang_time": "2.1",
            "descent_angle": "43.3",
            "peak_height": "5",
            "club_speed": "25",
            "pti": "1.30",
            "club": "undefined",
            "name": "Donny Knight",
            "timestamp": "2019-06-29T15:29",
            "session_type": "practice",
            "notes": {},
        },
        {
            "shot_num": "2",
            "hand": "R",
            "ball_speed": "32",
            "launch_angle": "24.8",
            "back_spin": "2560",
            "side_spin": "1040",
            "side_angle": "2.7",
            "offline_distance": "2",
            "carry": "18",
            "roll": "2",
            "total": "20",
            "hang_time": "1.4",
            "descent_angle": "26.2",
            "peak_height": "2",
            "club_speed": "28",
            "pti": "1.17",
            "club": "undefined",
            "name": "Donny Knight",
            "timestamp": "2019-06-29T15:29",
            "session_type": "practice",
            "notes": {},
        },
        {
            "shot_num": "3",
            "hand": "R",
            "ball_speed": "32",
            "launch_angle": "39.2",
            "back_spin": "2051",
            "side_spin": "416",
            "side_angle": "-6.4",
            "offline_distance": "-2",
            "carry": "21",
            "roll": "1",
            "total": "22",
            "hang_time": "1.9",
            "descent_angle": "41.7",
            "peak_height": "4",
            "club_speed": "25",
            "pti": "1.28",
            "club": "undefined",
            "name": "Donny Knight",
            "timestamp": "2019-06-29T15:29",
            "session_type": "practice",
            "notes": {},
        },
        {
            "shot_num": "4",
            "hand": "R",
            "ball_speed": "162",
            "launch_angle": "10.9",
            "back_spin": "4490",
            "side_spin": "1181",
            "side_angle": "-3.6",
            "offline_distance": "21",
            "carry": "252",
            "roll": "7",
            "total": "259",
            "hang_time": "7.4",
            "descent_angle": "45.7",
            "peak_height": "38",
            "club_speed": "115",
            "pti": "1.42",
            "club": "driver",
            "name": "Donny Knight",
            "timestamp": "2019-06-29T15:29",
            "session_type": "practice",
            "notes": {},
        },
        {
            "shot_num": "5",
            "hand": "R",
            "ball_speed": "160",
            "launch_angle": "15.4",
            "back_spin": "4215",
            "side_spin": "1642",
            "side_angle": "-3.0",
            "offline_distance": "40",
            "carry": "248",
            "roll": "8",
            "total": "256",
            "hang_time": "7.7",
            "descent_angle": "50.7",
            "peak_height": "45",
            "club_speed": "113",
            "pti": "1.42",
            "club": "driver",
            "name": "Donny Knight",
            "timestamp": "2019-06-29T15:29",
            "session_type": "practice",
            "notes": {},
        },
        {
            "shot_num": "6",
            "hand": "R",
            "ball_speed": "161",
            "launch_angle": "14.3",
            "back_spin": "3034",
            "side_spin": "615",
            "side_angle": "-5.9",
            "offline_distance": "-2",
            "carry": "271",
            "roll": "10",
            "total": "281",
            "hang_time": "7.5",
            "descent_angle": "41.4",
            "peak_height": "39",
            "club_speed": "111",
            "pti": "1.45",
            "club": "driver",
            "name": "Donny Knight",
            "timestamp": "2019-06-29T15:29",
            "session_type": "practice",
            "notes": {},
        },
    ]
    parser = RangeDataParser(TEST_RANGE_DATA)
    assert parser.json() == expected
