version: '3'

services: 
  upload: 
    container_name: skystats-upload
    image: skystats-upload
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    ports: 
      - "5000:5000"
    environment:
      OUTPUT_TYPE: api
      OUTPUT_LOCATION: http://localhost:8000/v1/shots/