version: '3'

services: 
  upload: 
    container_name: skystats-upload
    image: skystats-upload:0.1.0
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    ports: 
      - "5000:5000"
    environment:
      API_ENDPOINT: https://skytrakstats.com/api/v1/sessions/
      AUTH0_AUDIENCE: https://skytrakstats.com/api
      AUTH0_GRANT_TYPE: client_credentials
      AUTH0_URL: https://dk-test.auth0.com/oauth/token
    env_file:
      - creds.env