version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /apps/skystats/static/skystats:/skystats/static/
    ports:
      - "80:80"
      - "443:443"
