# Generated by Django 2.2.3 on 2019-07-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_num', models.IntegerField()),
                ('hand', models.CharField(choices=[('L', 'left'), ('R', 'right')], max_length=1)),
                ('ball_speed', models.IntegerField()),
                ('launch_angle', models.DecimalField(decimal_places=1, max_digits=3)),
                ('back_spin', models.IntegerField()),
                ('side_spin', models.IntegerField()),
                ('side_angle', models.DecimalField(decimal_places=1, max_digits=3)),
                ('offline_distance', models.IntegerField()),
                ('carry', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('total', models.IntegerField()),
                ('hang_time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('descent_angle', models.DecimalField(decimal_places=1, max_digits=3)),
                ('peak_height', models.IntegerField()),
                ('club_speed', models.IntegerField()),
                ('pti', models.DecimalField(decimal_places=2, max_digits=3)),
                ('club', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
