# Generated by Django 2.2.3 on 2019-07-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0003_auto_20190704_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
