# Generated by Django 2.2.3 on 2019-07-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0005_auto_20190712_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='shots.Session'),
        ),
    ]
