# Generated by Django 2.2.3 on 2019-08-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0006_auto_20190713_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.EmailField(default='dknight1010@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('timestamp', 'session_type'), name='unique_session'),
        ),
    ]
