# Generated by Django 2.2.3 on 2019-08-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0007_auto_20190804_1628'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user'], name='shots_sessi_user_30158e_idx'),
        ),
    ]
